### ISSUE TITLE
query_unavailability_transmission broken in commit  9f4364c

### ISSUE THREAD

**Issue by absvm** [EnergieID/entsoe-py#254] opened 2023-04-01 05:26 UTC
Fields `mrid` and `revisionnumber` were added to the unavailability parser in commit 400afb3. However, in the next commit 9f4364c these fields were removed again from the transmission headers (HEADERS_UNAVAIL_TRANSM). This breaks the parsing of transmission unavailabilities. 

Code to reproduce:

```
from entsoe import EntsoePandasClient
import pandas as pd

api_key = "b49b1494-3b57-406a-9b42-3f0cc1496c1d"

client = EntsoePandasClient(api_key=api_key)

start = pd.Timestamp('20230328', tz='Europe/Brussels')
end = pd.Timestamp('20230401', tz='Europe/Brussels')

result = client.query_unavailability_transmission('NL', 'GB', start=start, end=end)

print(result)
```

yields

```
Traceback (most recent call last):
  File "/Users/absvm/DEV/Python/venv/ENTSOE/lib/python3.9/site-packages/entsoe/decorators.py", line 44, in pagination_wrapper
    df = func(*args, start=start, end=end, **kwargs)
  File "/Users/absvm/DEV/Python/venv/ENTSOE/lib/python3.9/site-packages/entsoe/entsoe.py", line 1884, in query_unavailability_transmission
    df = parse_unavailabilities(content, "A78")
  File "/Users/absvm/DEV/Python/venv/ENTSOE/lib/python3.9/site-packages/entsoe/parsers.py", line 944, in parse_unavailabilities
    frame = _outage_parser(arc.read(f), headers, ts_func)
  File "/Users/absvm/DEV/Python/venv/ENTSOE/lib/python3.9/site-packages/entsoe/parsers.py", line 987, in _outage_parser
    df = pd.DataFrame.from_records(d, columns=headers)
  File "/Users/absvm/DEV/Python/venv/ENTSOE/lib/python3.9/site-packages/pandas/core/frame.py", line 2338, in from_records
    arrays, arr_columns = to_arrays(data, columns)
  File "/Users/absvm/DEV/Python/venv/ENTSOE/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 875, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/Users/absvm/DEV/Python/venv/ENTSOE/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 972, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 12 columns passed, passed data had 14 columns
```

We believe 9f4364c should be undone and Fields `mrid` and `revisionnumber` should be added to the HEADERS_UNAVAIL_TRANSM again:

```
HEADERS_UNAVAIL_TRANSM = ['created_doc_time',
                          'docstatus',
                          'mrid',
                          'revision',
                          'businesstype',
                          'in_domain',
                          'out_domain',
                          'qty_uom',
                          'curvetype',
                          'start',
                          'end',
                          'resolution',
                          'pstn',
                          'avail_qty'
                          ]
```

  This fixes the issue.

**Comment by LemuelKL** [comment] 2023-07-07 22:06
Duplicate of #219

**Comment by fboerman** [comment] 2023-07-20 12:08
closed for being duplicate

**Closed by fboerman** 2023-07-20 12:08 UTC
