### ISSUE TITLE
query_day_ahead_prices does not return the right time span sometimes

### ISSUE THREAD

**Issue by nima-mirzaei** [EnergieID/entsoe-py#187] opened 2022-06-14 14:10 UTC
from entsoe import EntsoePandasClient
    import pandas as pd

    client = EntsoePandasClient(api_key)

    dt_start = datetime.datetime.strptime("2022-06-06 23:00+0200", "%Y-%m-%d %H:%M%z")
    dt_end = dt_start + datetime.timedelta(hours=23)

    country_code = 'SE_3'

    DA_prices={}
    for i in range(4):
        start_datetime = pd.Timestamp(dt_start+datetime.timedelta(hours=i))
        end_datetime = pd.Timestamp(dt_end+datetime.timedelta(hours=i))
        DA_prices[i] = client.query_day_ahead_prices(country_code, start=start_datetime, end=end_datetime)
        print(len(DA_prices[i]))

Running the code above, I get the following lengths in the console: 24, 24, 23, 24. It seems the API sometimes does not return the right span. Or have I missed something here?

**Comment by fboerman** [comment] 2022-07-03 19:27
hi @nima-mirzaei  arent you accidentally going over a day light saving border?

**Comment by nima-mirzaei** [comment] 2022-07-21 07:48
Hi @fboerman! I don't think so. I think the shifting date for daylight saving in the EU is the last Sunday in March...

**Comment by fgenoese** [comment] 2022-08-11 13:09
Weird bug. I can confirm this also for other bidding zones and other dates. It happens when the end timestamp is exactly midnight, i.e.  in this case `2022-06-08 00:00:00+02:00`

On the other hand, running exactly the same code for `query_load()` always returns 23.

**Comment by jdtrebbien** [comment] 2022-08-11 16:44
I think I got it. I added the following `print()` statements into `query_day_ahead_prices` :
```
@year_limited
    def query_day_ahead_prices(
            self, country_code: Union[Area, str], start: pd.Timestamp,
            end: pd.Timestamp) -> pd.Series:
        """
        Parameters
        ----------
        country_code : Area|str
        start : pd.Timestamp
        end : pd.Timestamp

        Returns
        -------
        pd.Series
        """
        area = lookup_area(country_code)
        text = super(EntsoePandasClient, self).query_day_ahead_prices(
            country_code=area, start=start, end=end)
        series = parse_prices(text)
        print('After parse_prices:', len(series))
        series = series.tz_convert(area.tz)
        print('After tz_convert:', len(series))
        series = series.truncate(before=start, after=end)
        print('After truncate:', len(series))
        return series
```

This gives me the following output when running the example code:

```
After parse_prices: 48
After tz_convert: 48
After truncate: 24
24
After parse_prices: 24
After tz_convert: 24
After truncate: 24
24
After parse_prices: 24
After tz_convert: 24
After truncate: 23
23
After parse_prices: 48
After tz_convert: 48
After truncate: 24
24
```

The mistake happens after the `series.truncate`. The problem is in the timezone returned by the API. Since the timezone is UTC and we change it to the timezone we use we will miss some data after truncating with our initial timestamps. When `start`, `end` are not near midnight it doesnt matter, because we will get more data then needed since the API returns a whole day, even if we only need one hour from that day. 

While testing this I even found another error:
The data returned from the API is alway shifted by one hour, I guess this could be a problem with opening/closing times of timeframes. 

I guess the "easiest" fix for this would be to just add one day on each side of the time range spanned by `start`, `end`. I will give this approach a try and make a PR if it's working. Otherwise Im also happy if someone has a better solution for this.

**Comment by jdtrebbien** [comment] 2022-08-11 16:57
I think the difference for `query_load` comes from the API returning the requested time_frame directly, but excluding the `end` hour just like indexing in python. It also format our given timestamps into UTC and then return the UTC timeframes. We just convert it back to our timezone which is then the correct timezone.

**Comment by fboerman** [comment] 2022-08-12 12:46
hi thanks @jdtrebbien for providing a fix I have merged it and will release a new version soon. thanks all!

**Closed by fboerman** 2022-08-12 12:46 UTC
