### ISSUE TITLE
DA prices query returns the wrong time span

### ISSUE THREAD

**Issue by bmorenods** [EnergieID/entsoe-py#358] opened 2024-10-22 12:39 UTC
I am using the DA price query and it returns me the wrong time span. I guess it always returns series with a maximum of 2398 length. I am using the 0.6.13 version.

```
from entsoe import EntsoePandasClient     
import pandas as pd

client = EntsoePandasClient(api_key='...')
client.query_day_ahead_prices("FR", start = pd.Timestamp("20240101", tz='UTC'), end = pd.Timestamp("20241021", tz='UTC'))
```
It returns:

```
2024-01-01 01:00:00+01:00     0.01
2024-01-01 02:00:00+01:00     0.00
2024-01-01 03:00:00+01:00    -0.01
2024-01-01 04:00:00+01:00    -0.03
2024-01-01 05:00:00+01:00    -0.02
                             ...
2024-04-09 19:00:00+02:00    11.74
2024-04-09 20:00:00+02:00     5.00
2024-04-09 21:00:00+02:00    14.72
2024-04-09 22:00:00+02:00     6.35
2024-04-09 23:00:00+02:00     7.15
Freq: 60min, Length: 2398, dtype: float64
```

**Comment by fboerman** [comment] 2024-10-22 21:58
I am sorry I cannot reproduce this with the latest version.  I did encounter an error with the truncation which I quickly fixed in a small new release of 0.6.14

Please try in a completely clean environment and double check the version you are using by doing print(entsoe.__version___) this should now be 0.6.14

**Closed by fboerman** 2024-10-22 21:58 UTC
