### ISSUE TITLE
Unable to Access Day-Ahead Prices in Python (version 0.6.9) – HTTP 400 Bad Request Error

### ISSUE THREAD

**Issue by Krthnanalyst** [EnergieID/entsoe-py#350] opened 2024-10-07 14:54 UTC
I'm experiencing an issue with accessing Day-Ahead prices using the ENTSOE API in Python (version 0.6.9). Despite updating to the latest version, I encounter the following error:

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://web-api.tp.entsoe.eu/api?documentType=A44&in_Domain=10YRO-TEL------P&out_Domain=10YRO-TEL------P&securityToken=**API_KEY**=201712302200&periodEnd=201901012200

My request period is set from 2018 until the current date, yet the error reflects incorrect timestamps.

I would appreciate any guidance or fixes to resolve this problem.

Thank you

**Comment by fboerman** [comment] 2024-10-07 15:00
That's probably a way too big request. If you need such bulk download then grab the csv from the sftp. This is not something this library can solve.

⁣Get BlueMail for Android ​

**Comment by bantu** [comment] 2024-10-07 20:48
The size of the time range accepted by ENTSOE seems to have changed. We are seeing:
```
<Reason>
<code>999</code>
<text>
Provided time interval (2021-12-30T23:00Z[UTC] - 2023-01-01T23:00Z[UTC]) is larger than maximum allowed period 'P1Y' for 'ENERGY_PRICES:XML' export.
</text>
</Reason>
```

**Comment by Krthnanalyst** [comment] 2024-10-08 06:32
I encountered a problem when calculating date ranges using datetime.datetime.now(). When I calculate the date range from 2024-01-01 to datetime.datetime.now(), everything works as expected. However, if I try to calculate from 2023-01-01 to datetime.datetime.now(), it no longer functions properly. Additionally, when I attempt to calculate a range between 2023-01-01 and 2024-01-01, I receive an error as well. Interestingly, this was not an issue last week, as I was able to successfully calculate date ranges from as far back as 2018-01-01 to datetime.datetime.now(). Any help or suggestions for troubleshooting would be greatly appreciated!

**Comment by NewEnergyAnalyst** [comment] 2024-10-08 08:34
Thanks for comments. I have also the same problem. When I run the below code:

client.query_day_ahead_prices('RO', start=start, end=end)

I got the message: "Length mismatch: Expected axis has 94 elements, new values have 96 elements" What is the problem? What should I do?

**Comment by bantu** [comment] 2024-10-08 08:40
@NewEnergyAnalyst That looks like an issue not related to the ticket description.

**Comment by NewEnergyAnalyst** [comment] 2024-10-08 08:42
> @NewEnergyAnalyst That looks like an issue possibly unrelated to the ticket description.

I think, it is related to change about the time-range.

**Comment by bantu** [comment] 2024-10-08 08:48
The problem here seems to be as follows: `query_day_ahead_prices()` has a `@year_limited` annotation which ensures the method is not called with time frames larger than one year. This is possibly required to adhere to the limitations of the ENTSOE Web API. In `query_day_ahead_prices()` however, there is this code block: 
```
        # we do here extra days at start and end to fix issue 187
        text = super(EntsoePandasClient, self).query_day_ahead_prices(
            country_code=area,
            start=start-pd.Timedelta(days=1),
            end=end+pd.Timedelta(days=1)
        )
```
which extends the time frame requested by two days. This possibly exceed the limitation of 1 year. The problem is that the logic of `@year_limited` must be applied after the extra days are added, not before.

**Comment by fboerman** [comment] 2024-10-08 08:53
@NewEnergyAnalyst  that is a seperate issue please file a different issue for that
@bantu aaaah that makes sense, that is a stupid design bug from me then. I will try to see what is the best way to fix that! possibly make the year_limited decorator chop in slightly smaller blocks or have the query understand when its already chopped. it is also possible the issue that it tries to fix is now fixed by the new version handling the response better.

In the meantime the workaround is then to chop your own requests in smaller blocks.

**Comment by NewEnergyAnalyst** [comment] 2024-10-08 08:55
> The problem here seems to be as follows: `query_day_ahead_prices()` has a `@year_limited` annotation which ensures the method is not called with time frames larger than one year. This is possibly required to adhere to the limitations of the ENTSOE Web API. In `query_day_ahead_prices()` however, there is this code block:
> 
> ```
>         # we do here extra days at start and end to fix issue 187
>         text = super(EntsoePandasClient, self).query_day_ahead_prices(
>             country_code=area,
>             start=start-pd.Timedelta(days=1),
>             end=end+pd.Timedelta(days=1)
>         )
> ```
> 
> which extends the time frame requested by two days. This possibly results in requests exceeding the limitation of 1 year. The problem is that the logic of `@year_limited` must be applied after the extra days are added, not before.

Thanks

**Comment by bantu** [comment] 2024-10-08 09:07
Something like this might work.
```
    def query_day_ahead_prices(
            self, country_code: Union[Area, str],
            start: pd.Timestamp,
            end: pd.Timestamp,
            resolution: Literal['60min', '30min', '15min'] = '60min') -> pd.Series:
        """
        Parameters
        ----------
        resolution: either 60min for hourly values,
            30min for half-hourly values or 15min for quarterly values, throws error if type is not available
        country_code : Area|str
        start : pd.Timestamp
        end : pd.Timestamp

        Returns
        -------
        pd.Series
        """
        if resolution not in ['60min', '30min', '15min']:
            raise InvalidParameterError('Please choose either 60min, 30min or 15min')
        area = lookup_area(country_code)
        # we do here extra days at start and end to fix issue 187
        series = self._query_day_ahead_prices(
            area=area,
            start=start-pd.Timedelta(days=1),
            end=end+pd.Timedelta(days=1),
            resolution=resolution
        )
        series = series.truncate(before=start, after=end)
        # because of the above fix we need to check again if any valid data exists after truncating
        if len(series) == 0:
            raise NoMatchingDataError
        series = series.tz_convert(area.tz)
        return series

    @year_limited
    def _query_day_ahead_prices(
            self, area: Area,
            start: pd.Timestamp,
            end: pd.Timestamp,
            resolution: Literal['60min', '30min', '15min'] = '60min') -> pd.Series:
        text = super(EntsoePandasClient, self).query_day_ahead_prices(
            country_code=area,
            start=start,
            end=end
        )
        series = parse_prices(text)[resolution]
        if len(series) == 0:
            raise NoMatchingDataError
        return series
```

**Comment by Krthnanalyst** [comment] 2024-10-16 06:22
There is a news entry on the ENTSO-E website, which appeared the day before yesterday, regarding the download of energy prices:

Dear Transparency Platform users,

We would like to inform you that the yearly download functionality for Energy Prices [12.1.D] is not available on [the Transparency Platform website](https://newtransparency.entsoe.eu/market/energyPrices). You can download data from the SFTP server ([link to SFTP guide](https://transparency.entsoe.eu/content/static_content/Static%20content/knowledge%20base/SFTP%20guide.html)) or via REST API ([link to REST API guide](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html)).

After the migration of Day-Ahead Prices [12.1.D] to Energy Prices [12.1.D] the REST API returns a maximum 100 publications per API request. Therefore to query a 1-year time interval of data, you need to make several requests using the "offset" parameter.

The [REST API specification for Energy Prices [12.1.D]](https://documenter.getpostman.com/view/7009892/2s93JtP3F6#3b383df0-ada2-49fe-9a50-98b1bb201c6b) is updated accordingly.

Kind regards,
Transparency Platform team

**Closed** 2024-10-16 21:27 UTC
Labels: bug

**Comment by bantu** [comment] 2024-10-17 09:38
@fboerman You seem to have dropped ´series = series.tz_convert(area.tz)`, which alters return value and thus API contract.
