### ISSUE TITLE
Entsoe import error using old version of bs4

### ISSUE THREAD

**Issue by dsimpson1980** [EnergieID/entsoe-py#246] opened 2023-02-22 11:28 UTC
The requirements.txt doe not specify a version for beautifulsoup4.

When using beautifulsoup4<4.11.0 the below error is thrown when importing entsoe:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<redacted>\site-packages\entsoe\__init__.py", line 1, in <module>
    from .entsoe import EntsoeRawClient, EntsoePandasClient, __version__
  File "<redacted>\site-packages\entsoe\entsoe.py", line 9, in <module>
    from bs4.builder import XMLParsedAsHTMLWarning
ImportError: cannot import name 'XMLParsedAsHTMLWarning' from 'bs4.builder' 

requirements.txt should include:

beautifulsoup4>=4.11.0

**Comment by fboerman** [comment] 2023-02-22 17:06
duplicate of #239

**Closed by fboerman** 2023-02-22 17:06 UTC
