### ISSUE TITLE
query_unavailability_of_generation_units query output discrepancy

### ISSUE THREAD

**Issue by ZekiMuren** [EnergieID/entsoe-py#233] opened 2023-01-09 13:17 UTC
Dear Entsoe-py community,

It seems that there is sometimes an output discrepancy when using `client.query_unavailability_of_generation_units(country_code, start, end, docstatus=None, periodstartupdate=None, periodendupdate=None)` vs. using the **Entso-e REST API**.

What I’ve seen currently is that there was an outage of Herdecke (HERDECKE_H6, Generation Unit) on January 6th and I can only find this outage on the Entso-e website : Unavailability of Production and Generation Units or via `https://web-api.tp.entsoe.eu/api?securityToken=MYTOKEN&documentType=A80&businessType=A53&biddingZone_Domain=10YDE-RWENET---I&periodStart=202212110800&periodEnd=202302020900` (please add your own entso-e api securityToken as a parameter when using the REST API)

When I instead download the actual unavailability list with entsoe-py client  `client.query_unavailability_of_generation_units(country_code, start, end, docstatus=None, periodstartupdate=None, periodendupdate=None) ` then I only get old outages and not the current / last one from January 6th.
It seems not possible to retrieve the outage on January 6th for Herdecke via entsoe-py client.

Thank you in advance for your help

**Entsoe Webpage**

![image](https://user-images.githubusercontent.com/97170283/211311153-996c42ea-619a-48a5-a90c-f1c5b035218a.png)

**Using entsoe-py client**

![image](https://user-images.githubusercontent.com/97170283/211314636-4ad40744-d8f7-4ab3-a4bd-6db204d03556.png)

**Entsoe REST API**

![image](https://user-images.githubusercontent.com/97170283/211316846-19319d38-feb4-4aae-8cef-5edce1f1a266.png)

The same behaviour can be observed when querying data via entsoe-py client for the **last 60/100/200 days**.
The outages shown for a specific asset with a query for the last 100 days can be **shorter** than the outages shown for the last 60 days. Although the total size of the dataframe (length) increases for 60/100/200 days, meaning we are not stuck with a max query size issue.

**Comment by fboerman** [comment] 2023-11-16 15:44
hi @ZekiMuren sorry for the long wait. Interesting find, I am not sure what is exactly going wrong but do you think it might be related to the to heavy handed duplication removal as discussed in #234 ?

**Comment by awarsewa** [comment] 2024-01-10 10:15
Hi @fboerman 
It is indeed related to the deletion of duplicates.
Also with the recently merged pull request this issue is not fixed.
The problem is that the index of the unavailability entries is their submission time.
Since unavailabilities for i.e. multiple machines/units that belong to one plant are submitted at the same time, these are treated as duplicates. The current implementation of dealing with duplicates does not handle this.
I propose to add an exception for unavailabilty queries in the decorators as follows:
```python
if func.__name__ != '_query_unavailability':
```
and encapsulate the duplicate removal code in this if-statement.

**Comment by fboerman** [comment] 2024-01-26 09:38
hi @awarsewa that seems like a good solution. I would however like to test this. unavailability is always quite complex, could you provide me a clear code snippit to check output before and after this change? Then I will implement and test it. Thanks in advance!

**Comment by fboerman** [comment] 2024-01-31 09:20
@awarsewa  great! I will take a look and close this issue then

**Closed by fboerman** 2024-01-31 09:20 UTC
Labels: bug, help wanted
