### ISSUE TITLE
Installation: Requirements for BeautifulSoup not specified

### ISSUE THREAD

**Issue by StefaE** [EnergieID/entsoe-py#223] opened 2022-12-05 21:52 UTC
In ./requirements.txt: BeautifulSoup version is not specified, should say something like `beautifulsoup4>=4.11.1` 

Maybe some slightly older versions still work, but:

- Old versions don't contain `XMParsedAsHTMLWarning` - but also don't raise such a warning (for me, old is <= 4.9.2)
- New versions write a warning which can be ignored (as is done by the code) - but need find it in bs4.builder (for me, new is >= 4.11.1)

(Of course, nicer would be a code refactoring ... but that's a bit on the long side, I guess)

**Comment by fboerman** [comment] 2022-12-19 16:08
as a principle I only want to support newish package versions. its indeed good to specify it, but then mainly in setup.py. requirements.txt doesnt really do anything and if you install it fresh it installs the latest anyway.

I am open to a pull request with suggestions on this ;)

**Comment by fboerman** [comment] 2023-02-15 07:04
duplicate of #239 will track it there

**Closed by fboerman** 2023-02-15 07:04 UTC
