### ISSUE TITLE
ImportError: cannot import name 'XMLParsedAsHTMLWarning' from 'bs4.builder' 

### ISSUE THREAD

**Issue by 399645** [EnergieID/entsoe-py#239] opened 2023-02-12 14:51 UTC
Hello, 

I am using Anaconda and Jupyter Notebook to run the code. I successfully installed the entsoe package (!pip install entsoe-py) but when I run "from entsoe import EntsoePandasClient" I get this error ImportError: cannot import name 'XMLParsedAsHTMLWarning' from 'bs4.builder'.

Any idea on what I need to do to resolve this.

Thanks in advance!

**Comment by StefaE** [comment] 2023-02-12 14:54
You need update BeautifulSoup4 to 4.11.0 or higher - unfortunatly this is not documented here, but [reported](https://github.com/EnergieID/entsoe-py/issues/223)

**Comment by 399645** [comment] 2023-02-12 15:12
@StefaE Thanks a lot for the quick response. I did see the report and tried to upgrade but the error remains. Please see picture attached.

Thanks again!
<img width="953" alt="BS4 Error" src="https://user-images.githubusercontent.com/53593631/218319333-d3bb8fe6-40a0-49fb-a1d2-a6fb35418c01.png">

**Comment by StefaE** [comment] 2023-02-12 17:59
confused ... you are somehow not picking up 4.11.2, but I can't say why from above.
In Jupyter, can you type:
```
import bs4
bs4.__version__
```

**Comment by fboerman** [comment] 2023-02-15 07:04
hi this is indeed a duplicate of #223 I should probably fix this in setup.py but forgot. will leave this one open as a reminder

**Closed** 2023-07-20 13:27 UTC
